# Site settings
title: Milan Dobrota
email: # your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts about programming, psychology and leadership.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.milandobrota.com" # the base hostname & protocol for your site
twitter_username: milandobrota
github_username: # milandobrota

# Build settings
markdown: kramdown
