# Site settings
title: Milan's Blog
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about programming, psychology and leadership. Maintained by Milan Dobrota.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.milandobrota.com" # the base hostname & protocol for your site
twitter_username: milandobrota
# github_username: milandobrota

permalink: /:title.html

# Build settings
markdown: kramdown
