# Site settings
title: Milan's Blog
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing my thoughts with the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.milandobrota.com" # the base hostname & protocol for your site
twitter_username: milandobrota
# github_username: milandobrota

permalink: date

# Build settings
markdown: kramdown
